### ISSUE TITLE
user can't upload large files

### ISSUE THREAD

**Issue by ghost** [Nerodesk/nerodesk#89]
Heroku:

> Heroku Application Error upon file upload completion: An error occurred in the application and your page could not be served. Please try again in a few moments.

Replication:

> 500mb txt file created with `fsutil` then uploaded.

@yegor256 response:

> It happens because the server is trying to put the entire file in memory first. But the maximum memory available is 128Mb.

**Comment by yegor256** [comment]
@karato that's definitely a bug, please dispatch it

**Comment by karato** [comment]
> @karato that's definitely a bug, please dispatch it

@yegor256 right, I added the `bug` tag

**Comment by karato** [comment]
@longtimeago this is your task

**Comment by longtimeago** [comment]
@k0r @yegor256 I've razed a question https://github.com/teamed/nerodesk/issues/111 related to the issue, but the problem is wider. I don't propose to increase server RAM as it will simply mask the problem.

Correct me if I'm wrong - there is no pure server-side solution. So, the problem can be split on two more or less independent parts:
1) Client side part - consider using https://github.com/blueimp/jQuery-File-Upload/wiki/Chunked-file-uploads to split large files and upload parts in separate requests. 
`Content-Range` can help us in this (http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.16)
2) Server side should be able to handle this request sequence and store parts either locally (MkDoc)  or in cloud (AwsDoc)

Also both `takes` and `jcabi-s3` should be modified to support files partitioning.
AmazonS3 already supports operations on file parts (see `AmazonS3.uploadPart()`) but `jcabi-s3` doesn't.

**Comment by k0r** [comment]
@longtimeago so the file is constructed on the server as each chunk less than or equal the configured server IO is uploaded until completion?

**Comment by longtimeago** [comment]
@k0r Sorry, didn't get your question ... could you please elaborate?

**Comment by k0r** [comment]
@longtimeago what is the eta for implementation for either method?

**Comment by longtimeago** [comment]
@k0r If we would have an appropriate client and partitioning support in `takes` and  `jcabi-s3` it shouldn't be too difficult for the server side.
Best case: 7h
Worst case: 20h - mostly because we would need to implement proper file-system based mocks.

But I don't feel myself very confident in this solution. Maybe, I've missed some important aspect. It would be cool to have @yegor256 's opinion as well.

**Comment by ghost** [comment]
@longtimeago I agree, let's see what @yegor256 says. thanks for your input on this situation.

**Comment by yegor256** [comment]
@longtimeago I totally agree that we should use that jQuery plugin (or something similar). But I don't agree with the complexity of the problem. If the plugin splits the file into parts and submits multiple requests, Takes should not be modified at all. It will just process requests individually and upload parts into S3. Also, jcabi-s3 doesn't need to be modified, we can use Amazon SDK directly. An instance of `AmazonS3` can be extracted from `Region`, using its `aws()` method: http://s3.jcabi.com/apidocs-0.9/com/jcabi/s3/Region.html

We're on the same page?

**Comment by longtimeago** [comment]
@k0r @yegor256 Yes, after deeper investigation of `takes` I see it can handle such requests  (TkWithHeades should help). And you are right about `Region.aws()`. We can use it for the low level access to Amazon S3.
Gonna start with server side test, thanks for hints.

**Comment by longtimeago** [comment]
PR https://github.com/teamed/nerodesk/pull/122 is available for review

**Comment by longtimeago** [comment]
@k0r Initial PR was merged. Please, close the issue if it's OK

**Comment by ghost** [comment]
@longtimeago thanks.

**Comment by longtimeago** [comment]
@k0r you forgot to close the issue :)

**Comment by ghost** [comment]
@longtimeago is this fix live yet? or included in the next version release?

**Comment by longtimeago** [comment]
@k0r the feature is long term. I've done the test emulating client side behavior (reproduce the "bug") and create 2 puzzles. That's how PDD actually works :)

**Comment by ghost** [comment]
@longtimeago just tested this again and received the same result. shouldn't we keep the discussion going until it's fixed?

**Comment by longtimeago** [comment]
@k0r You would not observe the desired behavior before feature is fully implemented. 
As task the task is marked "30min" the only thing I can do from start is to reproduce the issue with test and create several puzzles for the next developers. They will do the rest. If they couldn't finish in 30 min they will create another puzzles. Thus, feature is split by multiple small tasks.
Thus, current task should be closed, it's done (but feature is not finished)
Please, see the article about PDD (http://www.yegor256.com/2009/03/04/pdd.html) or contact @yegor256 for the explanation if something is still not clear.

**Comment by yegor256** [comment]
@longtimeago I think @k0r is right here, we have to see "something" before the ticket can be closed, see this: http://www.yegor256.com/2015/02/12/top-down-design.html At a very least the software should say something like "now you can't upload a file that is larger than X bytes"

**Comment by ghost** [comment]
@longtimeago thanks for the info.

**Comment by longtimeago** [comment]
@k0r @yegor256 fine, please, see the bug https://github.com/teamed/nerodesk/issues/111

**Comment by longtimeago** [comment]
@karato we are waiting for #111

**Comment by longtimeago** [comment]
@k0r @yegor256  what is the restriction for the actual upload size for now?
ok for 10 mb?

**Comment by ghost** [comment]
received this error with a 100mb file upload:

> java.util.NoSuchElementException: there are no headers by name "Content-Type" among 17 others
> at org.takes.misc.VerboseIterator.next(VerboseIterator.java:66)
> at org.takes.rq.RqMultipart.<init>(RqMultipart.java:86)
> at com.nerodesk.TkWrite.act(TkWrite.java:73)
> at org.takes.facets.auth.TsAuth$1.act(TsAuth.java:115)
> at org.takes.http.BkBasic.print(BkBasic.java:89)
> at org.takes.http.BkBasic.accept(BkBasic.java:73)
> at org.takes.http.BkSafe.accept(BkSafe.java:58)
> at org.takes.http.BkParallel$1.run(BkParallel.java:90)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
> at java.lang.Thread.run(Thread.java:745)

**Comment by karato** [comment]
> @karato we are waiting for #111

@longtimeago agreed, we'll wait for #111

**Comment by karato** [comment]
these 2 puzzles were created in this ticket: `89-6cce4050`, `89-4c8c8ec3`

**Comment by yegor256** [comment]
@k0r the problem you're getting with that 100Mb file upload is rather strange (the exception stacktrace you just posted). looks like your browser is not creating the HTTP request properly. please, report it in a separate ticket, since it's not related to the issue we're solving here

**Comment by karato** [comment]
I think we can continue, impediment #111 is closed

**Comment by ghost** [comment]
@yegor256 @karato @longtimeago just tested this with a 250mb file and received this error in chrome: `Error code: ERR_CONNECTION_ABORTED`

**Comment by longtimeago** [comment]
here is one more PR https://github.com/teamed/nerodesk/pull/140

**Comment by longtimeago** [comment]
@karato we are waiting for PR https://github.com/teamed/nerodesk/pull/140

**Comment by karato** [comment]
@longtimeago 7 days already, in 48 hours I will re-assign

added -30 to your rating, now it is equal to [+3726](http://www.netbout.com/b/35024?open=rating)

**Comment by longtimeago** [comment]
@karato we are STILL waiting for the PR #140

**Comment by karato** [comment]
@longtimeago task is too long, stop working with it. added -60 to your rating, now it is equal to [+3641](http://www.netbout.com/b/35024?open=rating)

**Comment by karato** [comment]
@pinaf this is your task

**Comment by pinaf** [comment]
@karato please assign someone else.

**Comment by karato** [comment]
> @karato please assign someone else.

@pinaf right, I will find someone else, no problem

**Comment by longtimeago** [comment]
@yegor256 @k0r can we close the task now? It was done in #140 but @karato reassigned it :(

**Comment by ghost** [comment]
@longtimeago tested again, received `'something went wrong! java.util.NoSuchElementException: there are no headers by name "Content-Type [...]"` -- less than 50% of the file uploaded each time.

**Comment by ghost** [comment]
![upload bug](http://www.nerodesk.com/nd_upload_bug_1.jpg)

**Comment by longtimeago** [comment]
@k0r it's known issue https://github.com/teamed/nerodesk/issues/133

**Comment by k0r** [comment]
@longtimeago we should probably keep this discussion going until this is fixed. [#133](https://github.com/teamed/nerodesk/issues/133) will implement a 404 page for the error here.

**Comment by longtimeago** [comment]
@karato let's wait for #133

**Comment by karato** [comment]
> @karato let's wait for #133 

@longtimeago yes, waiting for #133

**Comment by yegor256** [comment]
@karato assign @longtimeago back to this task pls

**Comment by karato** [comment]
> @karato assign @longtimeago back to this task pls

@yegor256 OK @longtimeago please go ahead, this task is yours

**Comment by karato** [comment]
#133 is closed, we were waiting for it.. maybe we can continue?

**Comment by longtimeago** [comment]
@k0r please, try to upload big-file now. #133 is finished

**Comment by ghost** [comment]
error persists with release tag 0.3.9.

**Comment by longtimeago** [comment]
@pinaf please, release new version. We need #133 to be seen in prod

**Comment by pinaf** [comment]
@longtimeago @yegor256 is the architect here

**Comment by longtimeago** [comment]
@pinaf ooops

**Comment by ghost** [comment]
@yegor256 lets release tag 0.3.10.

**Comment by yegor256** [comment]
@longtimeago @k0r 0.3.10 will be released in #133, in a few mins

**Comment by ghost** [comment]
error persists with release tag 0.3.10.

**Comment by k0r** [comment]
the project can't move forward until this error is fixed.

**Comment by longtimeago** [comment]
@k0r could you please be more precise. What error?  The one mentioned in #133 ?

**Comment by ghost** [comment]
@longtimeago [#89](https://github.com/teamed/nerodesk/issues/89)

**Comment by longtimeago** [comment]
@k0r sorry, but I have no way to access the logs from beta server. Could you please provide some logs?

**Comment by ghost** [comment]
@longtimeago I only have access to the CNAME record.

**Comment by longtimeago** [comment]
@k0r ok, so how I can see the error you've observed? I can't help without some more details.
The task is a bit overtimed

**Comment by k0r** [comment]
@longtimeago everything is posted sufficiently in this ticket.

**Comment by k0r** [comment]
@karato don't assign anymore tasks until this is fixed.

**Comment by k0r** [comment]
@yegor256 fix this or send me the final bill.

**Comment by karato** [comment]
@longtimeago we're on pause in the project, please stop working with this, until further information

**Comment by yegor256** [comment]
@longtimeago do you mind if I fix this problem myself?

**Comment by yegor256** [comment]
@karato please assign me to this task

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.14`

**Comment by yegor256** [comment]
@karato please close this issue, it's fixed

**Comment by karato** [comment]
@longtimeago the project is back on track, please continue

**Comment by longtimeago** [comment]
@yegor256 sure

**Comment by yegor256** [comment]
@longtimeago it's already fixed by myself, just waiting for ticket reassignment and closing

**Comment by longtimeago** [comment]
@yegor256 I know

**Comment by karato** [comment]
> @karato please assign me to this task

@yegor256 sure, the ticket is yours, go ahead

**Comment by karato** [comment]
> @karato please close this issue, it's fixed

@yegor256 Right, the issue is closed as you just asked

**Comment by longtimeago** [comment]
@yegor256 I'm not sure what was changed after my fix but now this issue is back again. I tried to upload 1Gb file and got OOM ...

**Comment by yegor256** [comment]
@longtimeago yes, now it's a different issue, inside nerodesk code, not in Takes any more, see #231

**Comment by karato** [comment]
@yegor256 done, I added **45 mins** in payment `000-aa373de5`, 1 hour and 55 mins spent to complete this

age=32 hours and 20 mins, that's why a bonus here for fast delivery

+45 added to your rating, current score is: [+9065](http://www.netbout.com/b/35008?open=rating)
